@startuml Context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

' Определение стилей для упрощения
HIDE_STEREOTYPE()

title Диаграмма Контекста (Level 1) \n MVP Открытие Депозитов

' Определяем Действующих Лиц (Users/Actors)
Person(client, "Клиент", "Пользователь, открывающий депозит (новый или существующий)")
Person(bck_manager, "Менеджер Бэк-офиса", "Подтверждает условия и открывает депозит в АБС")
Person(credit_manager, "Сотрудник Отдела Кредитования", "Предоставляет данные о кредитном риске")

' Определяем Систему (Software System)
System(bank_system, "Банковская Система (Наше Решение)", "Совокупность всех IT-систем и нового Интеграционного Слоя для MVP")

' Определяем Внешние Системы
System(cc_system, "Система Кол-центра", "Обработка заявок с Сайта. (React, Java Spring Boot)")
System(abs, "АБС (Core Banking)", "Ядро банковских операций. Хранит данные о клиентах, риске и счетах. (Delphi, Oracle)")
System(sms_gateway, "СМС-Шлюз", "Внешний сервис телеком-оператора для отправки СМС-оповещений")


' Отношения между Действующими Лицами и Системой
Rel(client, bank_system, "Использует для открытия депозита и получения ставок")
Rel(bck_manager, bank_system, "Подтверждает и обрабатывает заявки", "АБС / Новый СРС")
Rel(credit_manager, bank_system, "Предоставляет данные о кредитном риске", "АБС")

' Отношения Системы с Внешними Системах
Rel(bank_system, sms_gateway, "Отправляет СМС-уведомления", "Запрос через ИТ-отдел")
Rel_U(bank_system, abs, "Читает данные о счетах и риске, создает депозит")
Rel_U(bank_system, cc_system, "Получает заявки от новых клиентов")
Rel(cc_system, client, "Используется менеджером для приема звонков")
Rel(client, cc_system, "Звонит по вопросам депозитов")

' Добавляем связь для Сайта и Интернет-банка (они являются частью интерфейса клиента)
System_Ext(site, "Сайт Банка", "Канал для новых клиентов (PHP, React.js)")
System_Ext(ib, "Интернет-Банк", "Канал для существующих клиентов (.NET MVC 4.5)")
Rel(client, site, "Подает заявку на депозит")
Rel(client, ib, "Просмотр персонализированных ставок и открытие депозита")

@enduml